version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
        - ./app:/var/www/html/app
        - ./bootstrap:/var/www/html/bootstrap
        - ./config:/var/www/html/config
        - ./database:/var/www/html/database
        - ./public:/var/www/html/public
        - ./resources:/var/www/html/resources
        - ./routes:/var/www/html/routes
        - ./storage:/var/www/html/storage
        - ./tests:/var/www/html/tests
    depends_on:
      - mysql
    networks:
      - laravel
    restart: unless-stopped
    ports:
        - "8000:8080"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - laravel

  mailhog:
    build: ./mailhog
    logging:
      driver: 'none'
    restart: unless-stopped
    ports:
      - "9001:8025"
      - "1025:1025"
    networks:
      - laravel

networks:
  laravel:


volumes:
  dbdata:
